##################################################
############ COMPASSHUNT CONFIG ##################
##################################################

Configuration:
  TrackingMessage: '&8[&cCompassHunt&8] &7Tracking: &4'